### ISSUE TITLE
Does the subscript 'sp' mean the image level?

### ISSUE THREAD

**Issue by hxx-who** [zqhang/Accurate-WinCLIP-pytorch#2]
I just got a little confused. I guess the 'px' means the pixel level and 'sp' means the image level, is that right?
And  can 'ap' be considered equal to AUPR?
Maybe the question is naive, hope you forgive that, thanks!

**Comment by hxx-who** [comment]
and can 'aupro' be considered the same as 'PRO' ? or they are two different evaluation index?

**Comment by zqhang** [comment]
Exactly, that's right!

**Comment by hxx-who** [comment]
> Exactly, that's right!

Are all the four guesses right? thanks a lot!

**Comment by zqhang** [comment]
yes



---- Replied Message ----
| From | ***@***.***> |
| Date | 12/18/2023 19:31 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [zqhang/WinCLIP-pytorch] Does the subscript 'sp' mean the image level? (Issue #2) |

Exactly, that's right!

Are all the four guesses right? thanks a lot!
